### ISSUE TITLE
Bug: not working on mac

### ISSUE THREAD

**Issue by chrisgrieser** [Mom0aut/obsidian-search-everywhere#1]
- tried left shift
- tried right shift
- plugin is installed via BRAT & enabled
- nothing gets logged in the console

```
macOS 12.2.1
Obsidian 0.13.30
```

**Comment by Mom0aut** [comment]
hey i added macOS support pls try out the new version

**Comment by chrisgrieser** [comment]
yes, works nicely! thanks 😊
