### ISSUE TITLE
[BUG ?] Holding SHIFT triggers the Plugin Command

### ISSUE THREAD

**Issue by FelipeRearden** [Mom0aut/obsidian-search-everywhere#2]
Hello @Mom0aut !!!!

Just to let you know that if we hold the `SHIFT` button for 2 seconds or more, triggers the command the same way that if we hit shift 2 times. 
- Version `1.0.7`
- Windows 7
- Obsidian `0.13.23`

Many times I use `SHIFT+Letter` to capitalize a letter in for example New York or USA for example. 

I don’t know if is possible to avoid this while holding SHIFT or to increase the time until triggers when holding the button.  :)

Thanks for reading this! 

Have a great day!!!!!!

**Comment by Mom0aut** [comment]
thank you for your report, this bug should be fixed with the new version 1.0.9

**Comment by FelipeRearden** [comment]
> thank you for your report, this bug should be fixed with the new version 1.0.9

Thank you very much @Mom0aut for your reply and for the quick fix !!!!!

Working perfect on version 1.0.9 - Obsidian 0.13.23

Have a great day!!!!!
